services:
    solr:
        image: ebispot/ols-solr:latest
        environment:
          - SOLR_HOME=/mnt/solr-config
        #ports:
        #  - 8983:8983
        volumes:
          - ols-solr-data:/var/solr
          - ./ols-solr/src/main/solr-5-config:/mnt/solr-config
        command: ["-Dsolr.solr.home=/mnt/solr-config", "-Dsolr.data.dir=/var/solr", "-f"]

    mongo:
      image: mongo:3.2.9
      #ports:
      #    - 27017:27017
      volumes:
          - ols-mongo-data:/data/db
      command:
          - "--quiet"

    # For easier development, expect olsync as a sibling directory. Move to Git submodule later.
    olsync:
      build: ../olsync
      environment:
        - OLSYNC_API_URLS=${OLSYNC_API_URLS}
        - OLSYNC_CONFIG_FILE=/app/obo-config.yaml
        - OLSYNC_MAX_ONTOLOGIES=${OLSYNC_MAX_ONTOLOGIES}
      volumes:
        - olsync:/app

    maven-builder:
      build: .
      volumes:
          - package:/package

    ols-config-importer:
      build: ./ols-apps/ols-config-importer
      environment:
        - spring.data.mongodb.host=mongo
        - ols.ontology.config=file:///config/ols-config.yaml
        - ols.obofoundry.ontology.config=file:///olsync/obo-config.yaml
      volumes:
        - olsync:/olsync
        - ./config:/config
        - package:/package
      depends_on:
        mongo:
          condition: service_started
        olsync:
          condition: service_completed_successfully
      restart: on-failure:2

    ols-indexer:
      build: ./ols-apps/ols-indexer
      environment:
        - spring.data.solr.host=http://solr:8983/solr
        - spring.data.mongodb.host=mongo
      volumes:
        - ols-neo4j-data:/mnt/neo4j
        - ols-downloads:/mnt/downloads
        - package:/package
        - ./config:/config
      depends_on:
        ols-config-importer:
          condition: service_completed_successfully

    ols-web:
      build: ./ols-web
      depends_on:
        ols-indexer:
          condition: service_completed_successfully
      links:
        - solr
        - mongo
      environment:
        - ols.customisation.debrand=true
        - spring.data.solr.host=http://solr:8983/solr
        - spring.data.mongodb.host=mongo
        - ols.customisation.logo=/img/logo-blue.svg
        - ols.customisation.title=Anthropological Notation Ontology
        - ols.customisation.short-title=ANNO
        - ols.customisation.web=https://annosaxfdm.de
        - ols.customisation.twitter=
        - ols.customisation.org=
        - ols.customisation.backgroundImage=/img/background_trial.jpg
        - ols.customisation.backgroundColor=#0080FF
        - ols.customisation.issuesPage=https://github.com/annosaxfdm/ols/issues
        - ols.customisation.supportMail=
        - OLS_HOME=/mnt/
      volumes:
        - ols-neo4j-data:/mnt/neo4j
        - ols-downloads:/mnt/downloads
        - package:/package
      ports:
      - ${OLS_WEB_PORT}:8080

volumes:
    ols-solr-data:
    ols-mongo-data:
    ols-neo4j-data:
    ols-downloads:
    package:
    olsync:
