
services:
    solr:
        image: ebispot/ols-solr:latest
        environment:
          - SOLR_HOME=/mnt/solr-config
        ports:
          - 8983:8983
        volumes:
          - ols-solr-data:/var/solr
          - ./ols-solr/src/main/solr-5-config:/mnt/solr-config
        command: ["-Dsolr.solr.home=/mnt/solr-config", "-Dsolr.data.dir=/var/solr", "-f"]

    mongo:
      image: mongo:3.2.9
      ports:
          - 27017:27017
      volumes:
          - ols-mongo-data:/data/db
      command:
          - "--quiet"

    # For easier development, expect olsync as a sibling directory. Move to Git submodule later.
    olsync:
      build: ../olsync
      environment:
        - OLSYNC_API_URLs=https://terminology.nfdi4chem.de/ts/api/ https://terminology.nfdi4ing.de/ts4ing/api/
        - OLSYNC_CONFIG_FILE=/app/obo-config.yaml
          # for testing
        - OLSYNC_MAX_ONTOLOGIES=1
      volumes:
        - olsync:/app

    maven-builder:
      build: .
      volumes:
          - package:/package

    ols-config-importer:
      build: ./ols-apps/ols-config-importer
      environment:
        - spring.data.mongodb.host=mongo
      volumes:
        - olsync:/config
        - package:/package
      depends_on:
        mongo:
          condition: service_started
        olsync:
          condition: service_completed_successfully
      restart: on-failure:2

    ols-indexer:
      build: ./ols-apps/ols-indexer
      environment:
        - spring.data.solr.host=http://solr:8983/solr
        - spring.data.mongodb.host=mongo
      volumes:
        - ols-neo4j-data:/mnt/neo4j
        - ols-downloads:/mnt/downloads
        - package:/package
      depends_on:
        ols-config-importer:
          condition: service_completed_successfully

    ols-web:
      build: ./ols-web
      depends_on:
        ols-indexer:
          condition: service_completed_successfully
      links:
        - solr
        - mongo
      environment:
        - spring.data.solr.host=http://solr:8983/solr
        - spring.data.mongodb.host=mongo
        - ols.customisation.logo=${LOGO}
        - ols.customisation.title=${TITLE}
        - ols.customisation.short-title=${SHORT_TITLE}
        - ols.customisation.web=${WEB}
        - ols.customisation.twitter=${TWITTER}
        - ols.customisation.org=${ORG}
        - ols.customisation.backgroundImage=${BACKGROUND_IMAGE}
        - ols.customisation.backgroundColor=${BACKGROUND_COLOR}
        - ols.customisation.issuesPage=${ISSUES_PAGE}
        - ols.customisation.supportMail=${SUPPORT_MAIL}
        - OLS_HOME=/mnt/
      volumes:
        - ols-neo4j-data:/mnt/neo4j
        - ols-downloads:/mnt/downloads
        - package:/package
      ports:
      - 8085:8080

volumes:
    ols-solr-data:
    ols-mongo-data:
    ols-neo4j-data:
    ols-downloads:
    package:
    olsync:
