FROM openjdk:8-jre-alpine
ENTRYPOINT ["java", "-jar", "/package/ols-config-importer.jar", "--ols.ontology.config=file:///config/ols-config.yaml","--ols.obofoundry.ontology.config=file:///config/obo-config.yaml"]
